version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gochecknoinits
          - gocognit
        path: (.+)_test\.go
      - linters:
          - gochecknoglobals
          - gochecknoinits
        path: cmd/(.+)\.go
      - linters:
          - gochecknoglobals
        path: main.go
      - linters:
          - ireturn
        path: cmd/internal/flag/flag.go
      - linters:
          - gochecknoglobals
        path: meta/meta.go
      - linters:
          - cyclop
          - funlen
          - ireturn
        path: convert/encoding.go
      - linters:
          - gosec
          - lll
        path: info/detail.go
      - linters:
          - gosec
        path: internal/mock/mock.go
      - linters:
          - err113
        path: logs/logs_test.go
      - linters:
          - ireturn
        path: table/table.go
      - linters:
          - gochecknoglobals
          - ireturn
        path: xud/xud.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
