# golangci-lint is a fast Go linters runner.
# https://golangci-lint.run 
#
# golangci-lint run
linters:
  enable-all: true
  disable:
    - interfacer        # deprecated
    - scopelint         # deprecated
    - golint            # deprecated
    - maligned          # deprecated
    - deadcode          # deprecated
    - ifshort           # deprecated
    - nosnakecase       # deprecated
    - varcheck          # deprecated
    - exhaustivestruct  # deprecated
    - structcheck       # deprecated

    - depguard          # unwanted, as it requires a list of packages
    - exhaustive        # too much boilerplate
    - exhaustruct       # too many values in struct literal (opinionated)
    - wrapcheck         # wrapping 3rd party errors are unnecessary (opinionated)
    - varnamelen        # doesn't allow short vars (opinionated)
    - goimports         # conflicts with gci
    - nlreturn          # opinionated
    - wsl               # opinionated
    #- paralleltest      # temp disabled

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 15

issues:
  exclude-rules:
    - path: 'cmd/(.+)\.go'
      linters:
        - gochecknoglobals
        - gochecknoinits
    - path: main.go
      linters:
        - gochecknoglobals
    - path: pkg/info/detail.go
      linters:
        - lll
    - path: cmd/internal/flag/flag.go
      linters:
        - ireturn
    - path: pkg/logs/logs_test.go
      linters:
        - goerr113
    - path: meta/meta.go
      linters:
        - gochecknoglobals
    - path: pkg/table/table.go
      linters:
        - ireturn
    - path: pkg/xud/xud.go
      linters:
        - gochecknoglobals
        - ireturn