# .goreleaser.yml
#
# test the config:
# goreleaser check
# goreleaser release --snapshot --clean
#
# create a version tag and push it:
# git tag -a v0.1.0 -m "First release"
# git push origin v0.1.0

project_name: retrotxtgo
# make a variable description

before:
  hooks:
    - go mod tidy
builds:
  - id: Linux_Intel
    goos: ['linux']
    goarch: ['amd64']
  - id: macOS
    goos: ['darwin']
    goarch: ['amd64', 'arm64']
  - id: Windows
    goos: ['windows']
    goarch: ['amd64']
universal_binaries:
  - id: macOS
    name_template: "{{ .ProjectName }}"
    replace: true

archives:
  - id: Linux_Intel
    builds: ['Linux_Intel']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: Linux arm
    builds: ['Linux arm']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: macOS
    builds: ['macOS']
    format: tar.gz
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  - id: Windows
    builds: ['Windows']
    format: zip
    files:
    - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: Linux
    builds: ['Linux_Intel']
    file_name_template: "{{ .ProjectName }}"
    vendor: Ben Garrett.
    homepage: https://retrotxt.com/go
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: Read legacy codepage encoded textfiles in a modern Unicode terminal.
    license: LGPL 3.0
    formats:
      - apk
      - deb
      - rpm

scoops:
  - name: retrotxt
  #- url_template: "ttps://github.com/bengarrett/retrotxtgo/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  - commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
  - commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  - homepage: https://retrotxt.com/go
  - description: Read legacy codepage encoded textfiles in a modern Unicode terminal.
  - license: LGPL 3.0
  # Setting this will prevent goreleaser to actually try to commit the updated
  # manifest leaving the responsibility of publishing it to the user.
  # If set to auto, the release will not be uploaded to the scoop bucket
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Default is false.
  - skip_upload: auto
  # Repository to push the generated files to.
  - repository:
      owner: bengarrett
      name: retrotxtgo
      branch: dev

changelog:
  skip: false
  use: git

upx:
  - 
    enabled: true
    ids: [Linux_Intel, Windows]
    # Valid options are from '1' (faster) to '9' (better), and 'best'.
    compress: best
    # Whether to try LZMA (slower).
    lzma: true
    # Whether to try all methods and filters (slow).
    brute: true
