package version

// Code generated by go generate; ignore.

// B holds the build and version information.
var B = Build{
	Commit:  "n/a",
	Date:    "2020-07-08T09:47:40+10:00",
	Domain:  "retrotxt.com",
	Version: "v0.0.19",
}
