package version

// Code generated by go generate; ignore.

// B holds the build and version information.
var B = Build{
	Commit:  "n/a",
	Date:    "2020-07-01T15:38:41+10:00",
	Domain:  "retrotxt.com",
	Version: "v0.0.16",
}
