# RetroTxt Go goreleaser.yaml file.
# Documentation at http://goreleaser.com
# Go environments https://golang.org/doc/install/source#environment
project_name: retrotxt
release:
  draft: false # setting to true breaks scoop
  prerelease: auto
before:
  hooks:
    - go mod download
    #- gosec ./...
    #- go generate ./... # this will create a dirty state
env:
  - CGO_ENABLED=0
  - GO111MODULE=on
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
builds:
  # upx compressed binaries
  - main: ../main.go
    id: retrotxt
    binary: retrotxt
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
    hooks:
      post:
        # -qq suppresses errors as freebsd is not supported
        - upx -qq "{{ .Path }}"
  # no upx compression
  - main: ../main.go
    id: uncompressed
    binary: retrotxt
    goos:
      - darwin
      - freebsd
    goarch:
      - amd64
  # linux for rpm
  - main: ../main.go
    id: rpm
    binary: retrotxt
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        # -qq suppresses errors as freebsd is not supported
        - upx -qq "{{ .Path }}"
archives:
  - name_template: "retrotxt_{{ if .Arm }}raspberry{{ .Arm }}{{ else }}{{ .Os }}{{ end }}"
    builds:
      - retrotxt
      - uncompressed
    replacements:
      darwin: macos
      freebsd: freebsd
      linux: linux
      windows: windows
      6: "_pi-zero" # VFPv1
      7: "_pi" # VFPv3
      386: ""
      amd64: ""
    format_overrides:
      - goos: darwin
        format: zip
      - goos: windows
        format: zip
brews:
  - skip_upload: auto
    github:
      owner: bengarrett
      name: homebrew-tap
    folder: Formula
    homepage: https://retrotxt.com/go
    description: RetroTxt is the tool that turns ANSI, ASCII, NFO text into in-browser HTML.
nfpms:
  - id: "deb"
    file_name_template: "retrotxt_{{ if .Arm }}raspberry{{ .Arm }}{{ else }}{{ .Os }}{{ end }}"
    builds:
      - retrotxt
    vendor: Ben Garrett
    homepage: https://retrotxt.com/go
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: RetroTxt is the tool that turns ANSI, ASCII, NFO text into in-browser HTML.
    license: LGPL 3.0
    replacements:
      6: "_pi-zero"
      7: "_pi"
    formats:
      - deb
  - id: "rpm"
    file_name_template: "retrotxt_{{ .Os }}"
    builds:
      - rpm
    vendor: Ben Garrett
    homepage: https://retrotxt.com/go
    maintainer: Ben Garrett <code.by.ben@gmail.com>
    description: RetroTxt is the tool that turns ANSI, ASCII, NFO text into in-browser HTML.
    license: LGPL 3.0
    formats:
      - rpm
scoop:
  bucket:
    owner: bengarrett
    name: retrotxtgo
  commit_author:
    name: Ben Garrett
    email: code.by.ben@gmail.com
  homepage: https://retrotxt.com/go
  description: RetroTxt is the tool that turns ANSI, ASCII, NFO text into in-browser HTML.
  license: LGPL 3.0
