# RetroTxt Go goreleaser.yaml file.
# Documentation at http://goreleaser.com
project_name: retrotxt
release:
  draft: true
  prerelease: auto
before:
  hooks:
    - go mod download
    #- gosec ./...
    - go generate ./...
builds:
  # upx compressed binaries
  - main: ../main.go
    binary: retrotxt
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    # https://golang.org/doc/install/source#environment
    goos:
      - darwin
      #      - freebsd
      - linux
      - windows
    goarch:
      - amd64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
    hooks:
      post:
        # -qq suppresses errors as freebsd is not supported
        - upx -qq "{{ .Path }}"
archives:
  - name_template: "RetroTxt_{{ if .Arm }}RaspberryPi{{ .Arm }}{{ else }}{{ .Os }}{{ end }}"
    replacements:
      darwin: macOS
      freebsd: FreeBSD
      linux: Linux
      windows: Windows
      6: "-1" # VFPv1
      7: "-2+" # VFPv3
      386: ""
      amd64: ""
    format_overrides:
      - goos: darwin
        format: zip
      - goos: windows
        format: zip
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
